server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: desc-cf-service
          uri: lb://desc-cf-service
          predicates:
            - Path=/desccf/**
        - id: desc-de-service
          uri: lb://desc-de-service
          predicates:
            - Path=/descde/**
        - id: desc-np-service
          uri: lb://desc-np-service
          predicates:
            - Path=/descnp/**
        - id: rack-service
          uri: lb://rack-service
          predicates:
            - Path=/rack/**
        - id: reportes-service
          uri: lb://reportes-service
          predicates:
            - Path=/reportes/**
        - id: reservas-comprobantes-service-users
          uri: lb://reservas-comprobantes-service
          predicates:
            - Path=/user/**
        - id: reservas-comprobantes-service-bookings
          uri: lb://reservas-comprobantes-service
          predicates:
            - Path=/reservas/**
        - id: reservas-comprobantes-service-receipts
          uri: lb://reservas-comprobantes-service
          predicates:
            - Path=/comprobantes/**
        - id: tarifas-service
          uri: lb://tarifas-service
          predicates:
            - Path=/tarifas/**