apiVersion: apps/v1
kind: Deployment
metadata:
  name: rack-service-deployment
  labels:
    app: rack-service-deployment
spec:
  selector:
    matchLabels:
      app: rack-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: rack-service-deployment
    spec:
      containers:
        - name: rack-service
          image: tgustafsson/rack-service:latest
          ports:
            - containerPort: 8096
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_RACK
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_RACK
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_RACK
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_RACK
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_RACK