apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportes-service-deployment
  labels:
    app: reportes-service-deployment
spec:
  selector:
    matchLabels:
      app: reportes-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: reportes-service-deployment
    spec:
      containers:
        - name: reportes-service
          image: tgustafsson/reportes-service:latest
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REPORTES
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REPORTES
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_REPORTES
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REPORTES
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REPORTES