apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarifas-service-deployment
  labels:
    app: tarifas-service-deployment
spec:
  selector:
    matchLabels:
      app: tarifas-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: tarifas-service-deployment
    spec:
      containers:
        - name: tarifas-service
          image: tgustafsson/tarifas-service:latest
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_TARIFAS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_TARIFAS
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_TARIFAS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_TARIFAS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_TARIFAS